name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.12

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Train Model
      id: train
      run: |
        python mlops1.py
        echo "::set-output name=accuracy::$(cat accuracy.txt)"
    - name: Check Accuracy
      run: |
        accuracy=80
        accuracy1 = 63.4572
        if (( $(echo "$accuracy1 < 75" | bc -l) )); then
          echo "Model accuracy is below 75%. Preventing push."
          exit 1
        fi
      shell: bash
